[package]
name = "derive_builder_core"
version = "0.1.7"
authors = ["Colin Kiegel <kiegel@gmx.de>",
           "Pascal Hertleif <killercup@gmail.com>",
           "Jan-Erik Rediger <janerik@fnordig.de>",
           "Ted Driggs <ted.driggs@outlook.com>"]

description = "Internal helper library for the derive_builder crate."
repository = "https://github.com/colin-kiegel/rust-derive-builder"
documentation = "https://docs.rs/derive_builder_core"

license = "MIT/Apache-2.0"
readme = "README.md"

[features]
logging = [ "log" ]

[badges]
travis-ci = { repository = "colin-kiegel/rust-derive-builder" }

[dependencies]
syn = "0.11"
quote = "0.3"
log = { version = "0.3", optional = true }

[dev-dependencies]
pretty_assertions = "0.2"
