[package]
name = "derive_builder_core"
version = "0.4.1"
authors = ["Colin Kiegel <kiegel@gmx.de>",
           "Pascal Hertleif <killercup@gmail.com>",
           "Jan-Erik Rediger <janerik@fnordig.de>",
           "Ted Driggs <ted.driggs@outlook.com>"]

description = "Internal helper library for the derive_builder crate."
repository = "https://github.com/colin-kiegel/rust-derive-builder"
documentation = "https://docs.rs/derive_builder_core"

license = "MIT/Apache-2.0"
readme = "README.md"

[features]
logging = [ "log" ]

[badges]
travis-ci = { repository = "colin-kiegel/rust-derive-builder" }

[dependencies]
darling = "0.8.5"
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["full", "extra-traits"] }
log = { version = "0.4", optional = true }

[dev-dependencies]
pretty_assertions = "0.5"
